//! Survivalist: Invisible Strain mod. Rust cdylib loaded by
//! Unityforge.Shim.Survivalist through the game's official mod
//! loader.
//!
//! Bootstrap path:
//! 1. The game's `Story.LoadDLLs()` loads
//!    `Unityforge.Shim.Survivalist.dll` from the mod's DLLs
//!    folder and invokes the global `Main.Load()`.
//! 2. `Main.Load` locates `survivalist_mod.unityforge.dll` in the
//!    mod folder, `LoadLibrary`s it, and calls
//!    `unityforge_init(bridge)`.
//! 3. `unityforge_init` is generated by the `unityforge_mod!`
//!    macro below; it stores the bridge, then calls `on_init`.
//! 4. `on_init` registers the framework's generic ops and the
//!    Unity-side selectors: the HTTP control plane for live
//!    research (walk_class / inspect_object / read_field /
//!    write_field / invoke_method / list_singletons / ...).
//! 5. The shim's driver GameObject Update calls `unityforge_tick`
//!    every frame; `Main.Unload()` (story switch) shuts the
//!    generation down and a later `Load()` re-arms it.

mod chronicle;
mod common;
mod development;
mod genome;
mod growth;
mod horde;
mod infection;
mod murder;
mod predation;
mod rob;
mod steal;
mod storyteller;
mod survival;
mod trade;
mod war;

use unityforge::ModDef;

static MOD_INFO: ModDef = ModDef {
    name: "SurvivalistMod",
    version: "0.1.0",
    http_port: 17173,
    on_init: Some(on_init),
    on_tick: Some(on_tick),
    on_shutdown: Some(on_shutdown),
    tabs: &[],
};

fn on_tick(now: f32) {
    genome::persistence_tick(now);
    growth::tick(now);
    development::tick(now);
    survival::tick(now);
    steal::tick(now);
    trade::tick(now);
    rob::tick(now);
    murder::tick(now);
    storyteller::tick(now);
}

unityforge::unityforge_mod!(MOD_INFO);

fn on_init() {
    // Generic primitive ops (ping, walk_class, inspect_object,
    // read_field, write_field, invoke_method, list_ops, ...).
    unityforge::ops::register_builtins();

    // Selector resolvers (singleton:, static_instance:, class:,
    // first_class:, handle:).
    unityforge::selector::register_builtins();

    // No infections (operator directive): every injury enters
    // uninfected via a Character.AddInjury prefix.
    infection::install();

    // Faction war: generalized revenge trigger (AI-vs-AI wars)
    // + war_status / war_ignite ops. docs/faction-war.md.
    war::install();
    war::register_ops();

    // REAL growth, people half: repopulator disabled (operator-
    // locked) + refugee recruitment on the tick + growth_status.
    growth::install();
    growth::register_ops();

    // Structure growth (annex model): dev_status + dev_place probe.
    development::register_ops();

    // Survival-driven behavior: desperation ladder + survival_status.
    survival::register_ops();

    // The storyteller: the director that paces drama, with the horde
    // as its first rule. storyteller_status + storyteller_config ops.
    storyteller::register_ops();

    // A hot reload empties the steal/trade mission lists while
    // their squads survive in the game; reclaim the orphans.
    common::sweep_orphan_trade_squads();

    unityforge::mono::log(
        unityforge::mono::LogLevel::Info,
        "survivalist-mod: ready (ops + selectors installed)",
    );
}

fn on_shutdown() {
    // Flush the genome memory so a hot reload loses no lessons.
    genome::persist_now();
    unityforge::mono::log(
        unityforge::mono::LogLevel::Info,
        "survivalist-mod: shutdown",
    );
}
