//! What does the game do when a player clicks Singleplayer, Load
//! Game, then a save?
//!
//! Auto-load currently calls `LoadLevel` on the object named
//! `BP_HostLoadGameServer`. That is the host-a-server path: every
//! launch came up in a FRESH world, with a different world number
//! each time (5760, 244, 10776, 15820), rather than the save.
//! So `LoadLevel` there is the wrong call, or something has to be
//! set before it that the menu sets and we do not.
//!
//! Same method that solved the playtest notice (research.md
//! 26.5): find the widget the player's click actually reaches,
//! read its live function list, and look for the handler that
//! click runs. A Blueprint button handler is named after the
//! button it belongs to, so the name identifies it.
//!
//! EVERYTHING HERE IS READ-ONLY. The save rows carry a delete
//! button as well as a load button, and both are named only by
//! number (`Button_284`, `Button_372`), so nothing is called
//! until the printout says which is which.
//!
//! Run at the MAIN MENU, before loading anything:
//!
//! ```text
//! MISERY_DEBUG_PORT=17176 cargo test -p misery-mod --test research_singleplayer_load -- --test-threads=1 --nocapture
//! ```

mod common;
use common::api_or_skip;
use serde_json::json;

/// Parts of a class name worth looking for on the main menu.
/// `walk_class_chain` matches a fragment, so this finds classes
/// nobody has named yet, including whatever sits behind the
/// Singleplayer button.
const NEEDLES: &[&str] = &[
    "SinglePlayer",
    "Singleplayer",
    "LoadSave",
    "SaveGame",
    "LoadGame",
    "Host",
    "MainMenu",
];

/// Every live object on the main menu whose class name contains
/// one of the fragments above.
///
/// The point is the object NAMES. `BP_HostLoadGameServer` and
/// `BP_HostNewGameServer` are both instances of the one class
/// `BP_HostNewGameServer_C`, so the class alone does not say
/// which is which, and there may be a singleplayer counterpart
/// hiding the same way.
#[test]
fn live_menu_objects() {
    let Some(api) = api_or_skip() else { return };
    for needle in NEEDLES {
        let r = api.op("walk_class_chain", json!({ "needle": needle, "max": 64 }));
        if !r.ok {
            println!("\n=== {needle}: FAILED {:?}", r.error);
            continue;
        }
        let all = r.result["instances"].as_array().cloned().unwrap_or_default();
        // Templates inside a /Game/... package are not real
        // objects; calling one succeeds and does nothing.
        let live: Vec<&serde_json::Value> = all
            .iter()
            .filter(|i| {
                i["full_name"]
                    .as_str()
                    .map(|n| n.contains("/Engine/Transient"))
                    .unwrap_or(false)
            })
            .collect();
        println!(
            "\n=== {needle}: {} total, {} live",
            r.result["total"], live.len()
        );
        for i in live {
            println!("  {}", i["full_name"].as_str().unwrap_or("?"));
            println!("    {}", i["addr_selector"].as_str().unwrap_or("?"));
        }
    }
}

/// Classes on the load path. The first four are the widgets the
/// player clicks through; the last two are where the choice is
/// stored and acted on.
const LOAD_PATH: &[&str] = &[
    "BP_MainMenu_C",
    "BP_SingleplayerMenu_C",
    "BP_LoadGameMenu_C",
    "BP_LoadGameMenuPanel_C",
    "BP_HostNewGameServer_C",
    "BP_SGKGameInstance_C",
];

/// Words that mark a function worth reading twice.
const INTERESTING: &[&str] = &[
    "Load", "Save", "Slot", "Open", "Level", "Travel", "Start",
    "Single", "Host", "Server", "Button", "BndEvt", "Clicked",
];

/// Every function each widget on the load path can be told to
/// run, with the interesting ones marked.
///
/// A button handler generated by a Blueprint carries the button's
/// own name, e.g.
/// `BndEvt__..._Button_284_..._OnButtonClickedEvent__DelegateSignature`.
/// That is what the click runs, and it is what to call.
#[test]
fn load_path_functions() {
    let Some(api) = api_or_skip() else { return };
    for class in LOAD_PATH {
        let r = api.op("class_functions", json!({ "class": class }));
        if !r.ok {
            println!("\n=== {class}: FAILED {:?}", r.error);
            continue;
        }
        let fns = r.result["functions"].as_array().cloned().unwrap_or_default();
        println!("\n=== {class} ({} functions)", fns.len());
        println!("    {}", r.result["full_name"].as_str().unwrap_or("?"));
        for f in &fns {
            let name = f["name"].as_str().unwrap_or("?");
            let mark = if INTERESTING.iter().any(|w| name.contains(w)) { ">>" } else { "  " };
            println!(
                "{mark} {name:<70} parms={} bytes={}",
                f["num_parms"], f["parms_size"]
            );
        }
    }
}

/// What each save row holds and what its buttons are called.
///
/// One row per save. Each has two buttons named only by number,
/// one to load and one to delete, so the field list is the only
/// thing that ties a number to a save. Read-only: nothing is
/// called on a row here.
#[test]
fn save_row_contents() {
    let Some(api) = api_or_skip() else { return };
    for class in ["BP_LoadGameMenu_C", "BP_LoadGameMenuPanel_C"] {
        let live = modforge::client::walk_class_chain_instances(&api, class, 16);
        println!("\n=== {class}: {} live instance(s)", live.len());
        for w in &live {
            println!("\n-- {}", w.full_name);
            let r = api.op("inspect_address", json!({"addr": format!("0x{:X}", w.addr)}));
            if r.ok {
                println!("{}", serde_json::to_string_pretty(&r.result).unwrap_or_default());
            } else {
                println!("   inspect failed: {:?}", r.error);
            }
        }
    }
}

/// The two objects of class `BP_HostNewGameServer_C`, side by
/// side.
///
/// Auto-load picks the one named `BP_HostLoadGameServer` and
/// calls `LoadLevel` on it, and gets a new world. If the two
/// objects differ in a field, that field is what tells `LoadLevel`
/// to load rather than generate, and setting it is the missing
/// step.
#[test]
fn the_two_host_objects() {
    let Some(api) = api_or_skip() else { return };
    let live = modforge::client::walk_class_chain_instances(&api, "BP_HostNewGameServer_C", 16);
    println!("=== BP_HostNewGameServer_C: {} live instance(s)", live.len());
    for w in &live {
        println!("\n-- {}", w.full_name);
        let r = api.op("inspect_address", json!({"addr": format!("0x{:X}", w.addr)}));
        if r.ok {
            println!("{}", serde_json::to_string_pretty(&r.result).unwrap_or_default());
        } else {
            println!("   inspect failed: {:?}", r.error);
        }
    }
}

/// What the game intends to load right now, before anything is
/// clicked.
///
/// If the slot name is empty at the main menu, then the menu sets
/// it when a row is clicked, and auto-load has to set it too
/// rather than read it back. That is the difference between
/// loading the player's save and generating a new world.
///
/// Read-only: both calls are getters.
#[test]
fn what_the_game_intends_to_load() {
    let Some(api) = api_or_skip() else { return };
    let live = modforge::client::walk_class_chain_instances(&api, "BP_SGKGameInstance_C", 4);
    let Some(gi) = live.iter().find(|w| w.full_name.contains("/Engine/Transient")) else {
        println!("no live game instance");
        return;
    };
    println!("game instance: {}", gi.full_name);

    let flag = api.op(
        "call",
        json!({
            "class": "BP_SGKGameInstance_C",
            "function": "SGK GetLoadSaveGame",
            "instance_selector": gi.addr_selector,
            "parms_hex": "00",
        }),
    );
    common::show("SGK GetLoadSaveGame", &flag);

    let name = api.op(
        "call",
        json!({
            "class": "BP_SGKGameInstance_C",
            "function": "SGK GetSaveGameSlotName",
            "instance_selector": gi.addr_selector,
            "parms_hex": "0".repeat(32),
        }),
    );
    common::show("SGK GetSaveGameSlotName", &name);
    if let Some(hex) = name.result["parms_hex_after"].as_str() {
        println!("slot name: {:?}", read_fstring(&api, hex));
    }
}

/// Decode an `FString` parm block: `{ TCHAR* Data; int32 Num;
/// int32 Max; }`, UTF-16 characters.
fn read_fstring(api: &common::Api, parms_hex: &str) -> String {
    let bytes = hex_to_bytes(parms_hex);
    if bytes.len() < 16 {
        return String::new();
    }
    let ptr = u64::from_le_bytes(bytes[0..8].try_into().unwrap());
    let num = i32::from_le_bytes(bytes[8..12].try_into().unwrap());
    if ptr == 0 || num <= 0 {
        return String::new();
    }
    let r = api.op(
        "read_bytes",
        json!({
            "instance_selector": format!("addr:0x{ptr:X}"),
            "offset": 0,
            "length": (num as usize) * 2,
        }),
    );
    if !r.ok {
        return format!("<read_bytes failed: {:?}>", r.error);
    }
    let raw = hex_to_bytes(r.result["bytes_hex"].as_str().unwrap_or(""));
    let units: Vec<u16> = raw
        .chunks_exact(2)
        .map(|c| u16::from_le_bytes([c[0], c[1]]))
        .take_while(|c| *c != 0)
        .collect();
    String::from_utf16_lossy(&units)
}

fn hex_to_bytes(s: &str) -> Vec<u8> {
    (0..s.len() / 2)
        .filter_map(|i| u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).ok())
        .collect()
}
